### ISSUE TITLE
Could I add an SSD1306 128x64 pixel OLED display to each side?

### ISSUE THREAD

**Issue by bekkazy-k** [DreaM117er/Explorer-Keyboard-Blank#1]
Thank you for your work—it inspired me to create a similar keyboard but with SSD1306 128x64 pixel OLED displays on each side. I'm a beginner, so I’d appreciate any advice on whether it would be possible to add these displays

**Comment by DreaM117er** [comment]
Yes, it can, both OLED and trackpad use I2C communication protocols. But you need to add OLED code in your custom firmware.

**Comment by bekkazy-k** [comment]
Does this mean that I can use both the trackpad and display on one side at the same time?

**Comment by DreaM117er** [comment]
sure, you can call them out.

**Comment by DreaM117er** [comment]
Actually I often check crkbd and lily58's firmware to learn how to work. Even I am not an engineer.

**Comment by DreaM117er** [comment]
> Does this mean that I can use both the trackpad and display on one side at the same time?

https://docs.qmk.fm/features/oled_driver#other-examples
